[package]
name = "oracleHolderv21"
version = "2.1.1"
authors = []

[addresses]
deployer = "0xc698c251041b826f1d3d4ea664a70674758e78918938d1b3b237418ff17b4020"
owner = "0xc698c251041b826f1d3d4ea664a70674758e78918938d1b3b237418ff17b4020"
supra_framework = "0x1"
[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.oracle_corev2]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/oracle_core'

[dependencies.TIMEv5]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/time'

[dependencies.AEXIS_SMART_MATH_BETA]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/smart_math'

[dev-dependencies]
