[package]
name = "governancev1"
version = "2.1.1"
authors = []

[addresses]
deployer = "0x392727cb3021ab76bd867dd7740579bc9e42215d98197408b667897eb8e13a1f"
owner = "0x392727cb3021ab76bd867dd7740579bc9e42215d98197408b667897eb8e13a1f"
messager = "0x392727cb3021ab76bd867dd7740579bc9e42215d98197408b667897eb8e13a1f"
validator = "0x392727cb3021ab76bd867dd7740579bc9e42215d98197408b667897eb8e13a1f"
std = "0x1"
aptos_std = "0x1"
supra_framework = "0x1"
[dev-addresses]


[dependencies.core]
git = "https://github.com/Entropy-Foundation/dora-interface.git"
rev = "master"
subdir = "supra/testnet/core"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.pointsv1]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/points'

[dev-dependencies]
