[package]
name = "dungeonsPkg5"
version = "1.0.0"
authors = []

[addresses]
deployer = "0x281d0fce12a353b1f6e8bb6d1ae040a6deba248484cf8e9173a5b428a6fb74e7"
dev = "0x281d0fce12a353b1f6e8bb6d1ae040a6deba248484cf8e9173a5b428a6fb74e7"
developer ="0x281d0fce12a353b1f6e8bb6d1ae040a6deba248484cf8e9173a5b428a6fb74e7"
supra_framework = "0x1"
[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.testCore45]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/Game/sources/Core'


[dependencies.entitiesPkg6]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/Game/sources/Storage/Entities'

[dependencies.constantPkg4]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/Game/sources/Storage/Constant'
[dev-dependencies]
