[package]
name = "testPlayer27"
version = "2.1.1"
authors = []

[addresses]
deployer = "0x281d0fce12a353b1f6e8bb6d1ae040a6deba248484cf8e9173a5b428a6fb74e7"
dev = "0x281d0fce12a353b1f6e8bb6d1ae040a6deba248484cf8e9173a5b428a6fb74e7"
developer ="0x281d0fce12a353b1f6e8bb6d1ae040a6deba248484cf8e9173a5b428a6fb74e7"
supra_framework = "0x1"
[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.testCore45]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/Game/sources/Core'

[dependencies.itemsPkg5]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/Game/sources/Storage/Items'

[dependencies.perksPkg13]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/Game/sources/Storage/Perks'

[dependencies.expeditionsPkg9]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/Game/sources/Storage/Expeditions'

[dependencies.classesPkg11]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/Game/sources/Storage/Classes'

[dependencies.constantPkg4]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/Game/sources/Storage/Constant'

[dependencies.chancesPkg4]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/Game/sources/Storage/Chances'

[dependencies.accountsPkg5]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/Game/sources/Storage/Accounts'

[dependencies.testUtils10]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/Game/sources/Utils'

[dependencies.randomv1]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/Random'


[dev-dependencies]