[package]
name = "oracle_corev1"
version = "2.1.1"
authors = []

[addresses]
owner = "0x392727cb3021ab76bd867dd7740579bc9e42215d98197408b667897eb8e13a1f"
dev = "0x392727cb3021ab76bd867dd7740579bc9e42215d98197408b667897eb8e13a1f"
supra_framework = "0x1"
std = "0x1"
aptos_std = "0x1"
Extensions = "0x1" # For Prover to instantiate `{{Ext}}` in prelude.
[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.core]
git = "https://github.com/Entropy-Foundation/dora-interface.git"
rev = 'master'
subdir = 'supra/testnet/core'

[dependencies.governancev1]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/governance'

[dependencies.AptosStdlib]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-stdlib"

[dev-dependencies]
