[package]
name = "oracle_corev15"
version = "2.1.1"
authors = []

[addresses]
owner = "0x392727cb3021ab76bd867dd7740579bc9e42215d98197408b667897eb8e13a1f"
deployer = "0x392727cb3021ab76bd867dd7740579bc9e42215d98197408b667897eb8e13a1f"
aexis = "0x1928893148d317947c302185417e2c1d32640c6ef8521b48e1ae6308ab1a41c3"
supra_framework = "0x1"
[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.governance]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/governance'

[dependencies.time]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/time'

[dependencies.smart_math]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/smart_math'

[dev-dependencies]
