[package]
name = "oracle_core"
version = "2.1.1"
authors = []

[addresses]
deployer = "0xc698c251041b826f1d3d4ea664a70674758e78918938d1b3b237418ff17b4020"
owner = "0xc698c251041b826f1d3d4ea664a70674758e78918938d1b3b237418ff17b4020"
supra_framework = "0x1"
[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.core]
git = "https://github.com/Entropy-Foundation/dora-interface.git"
rev = 'master'
subdir = 'supra/testnet/core'

[dev-dependencies]