[package]
name = "smart_math"
version = "2.1.1"
authors = []

[addresses]
aexis = "0x1928893148d317947c302185417e2c1d32640c6ef8521b48e1ae6308ab1a41c3"
supra_framework = "0x1"
[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dev-dependencies]
