[package]
name = "Randomv15"
version = "2.1.1"
authors = []

[addresses]
deployer = "0xc5e7e76cbce04ac46b408d26fdb0ba3e0fbbbd6b0cd3f4f9bfc62466f6ab72c2"
owner = "0xc5e7e76cbce04ac46b408d26fdb0ba3e0fbbbd6b0cd3f4f9bfc62466f6ab72c2"
dev = "0xc5e7e76cbce04ac46b408d26fdb0ba3e0fbbbd6b0cd3f4f9bfc62466f6ab72c2"
supra_oracle = "0x5615001f63d3223f194498787647bb6f8d37b8d1e6773c00dcdd894079e56190"
supra_framework = "0x1"
[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.core]
git = "https://github.com/Entropy-Foundation/dora-interface.git"
rev = "master"
subdir = "supra/testnet/core"


[dev-dependencies]
