[package]
name = "oracleHolderv7"
version = "2.1.1"
authors = []

[addresses]
deployer = "0xc698c251041b826f1d3d4ea664a70674758e78918938d1b3b237418ff17b4020"
owner = "0xc698c251041b826f1d3d4ea664a70674758e78918938d1b3b237418ff17b4020"
dev = "0x392727cb3021ab76bd867dd7740579bc9e42215d98197408b667897eb8e13a1f"
supra_framework = "0x1"
[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.oracle_corev12]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/oracle_core'

[dependencies.time]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/time'

[dependencies.smart_math]
git = 'https://github.com/cnhuya/test.git'
rev = 'main'
subdir = 'modules/smart_math'

[dev-dependencies]
